<?php

/**
 * PayrollConfigTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PayrollConfigTable extends PluginPayrollConfigTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PayrollConfigTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PayrollConfig');
    }
    
     public static function getConfiguration(){
  
    return self::getInstance()->find(1);
    }
}