<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/02/27 05:59:24
sfConfig::add(array(
  'mod_earningsdeductions_enabled' => true,
  'mod_earningsdeductions_view_class' => 'sfPHP',
));
