<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('HsHrUniqueId', 'doctrine');

/**
 * BaseHsHrUniqueId
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $last_id
 * @property string $table_name
 * @property string $field_name
 * 
 * @method integer      getId()         Returns the current record's "id" value
 * @method integer      getLastId()     Returns the current record's "last_id" value
 * @method string       getTableName()  Returns the current record's "table_name" value
 * @method string       getFieldName()  Returns the current record's "field_name" value
 * @method HsHrUniqueId setId()         Sets the current record's "id" value
 * @method HsHrUniqueId setLastId()     Sets the current record's "last_id" value
 * @method HsHrUniqueId setTableName()  Sets the current record's "table_name" value
 * @method HsHrUniqueId setFieldName()  Sets the current record's "field_name" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHsHrUniqueId extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_unique_id');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('last_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('table_name', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('field_name', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}