<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('HsHrEmpChildren', 'doctrine');

/**
 * BaseHsHrEmpChildren
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $emp_number
 * @property decimal $ec_seqno
 * @property string $ec_name
 * @property date $ec_date_of_birth
 * @property HsHrEmployee $HsHrEmployee
 * 
 * @method integer         getEmpNumber()        Returns the current record's "emp_number" value
 * @method decimal         getEcSeqno()          Returns the current record's "ec_seqno" value
 * @method string          getEcName()           Returns the current record's "ec_name" value
 * @method date            getEcDateOfBirth()    Returns the current record's "ec_date_of_birth" value
 * @method HsHrEmployee    getHsHrEmployee()     Returns the current record's "HsHrEmployee" value
 * @method HsHrEmpChildren setEmpNumber()        Sets the current record's "emp_number" value
 * @method HsHrEmpChildren setEcSeqno()          Sets the current record's "ec_seqno" value
 * @method HsHrEmpChildren setEcName()           Sets the current record's "ec_name" value
 * @method HsHrEmpChildren setEcDateOfBirth()    Sets the current record's "ec_date_of_birth" value
 * @method HsHrEmpChildren setHsHrEmployee()     Sets the current record's "HsHrEmployee" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHsHrEmpChildren extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_emp_children');
        $this->hasColumn('emp_number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ec_seqno', 'decimal', 2, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('ec_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('ec_date_of_birth', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('HsHrEmployee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));
    }
}