<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmEmpsalaryDeductions', 'doctrine');

/**
 * BaseOhrmEmpsalaryDeductions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $deduction
 * @property string $emp_number
 * @property integer $amount
 * @property integer $is_recurrent
 * @property date $deduction_date
 * 
 * @method integer                 getId()             Returns the current record's "id" value
 * @method integer                 getDeduction()      Returns the current record's "deduction" value
 * @method string                  getEmpNumber()      Returns the current record's "emp_number" value
 * @method integer                 getAmount()         Returns the current record's "amount" value
 * @method integer                 getIsRecurrent()    Returns the current record's "is_recurrent" value
 * @method date                    getDeductionDate()  Returns the current record's "deduction_date" value
 * @method OhrmEmpsalaryDeductions setId()             Sets the current record's "id" value
 * @method OhrmEmpsalaryDeductions setDeduction()      Sets the current record's "deduction" value
 * @method OhrmEmpsalaryDeductions setEmpNumber()      Sets the current record's "emp_number" value
 * @method OhrmEmpsalaryDeductions setAmount()         Sets the current record's "amount" value
 * @method OhrmEmpsalaryDeductions setIsRecurrent()    Sets the current record's "is_recurrent" value
 * @method OhrmEmpsalaryDeductions setDeductionDate()  Sets the current record's "deduction_date" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmEmpsalaryDeductions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_empsalary_deductions');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('deduction', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('emp_number', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('amount', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('is_recurrent', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('deduction_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}