<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmTerminationDues', 'doctrine');

/**
 * BaseOhrmTerminationDues
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $termination_id
 * @property integer $emp_no
 * @property integer $payment
 * @property integer $deduction
 * @property string $description
 * @property string $amount
 * @property string $overtime_for_month
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method integer             getTerminationId()      Returns the current record's "termination_id" value
 * @method integer             getEmpNo()              Returns the current record's "emp_no" value
 * @method integer             getPayment()            Returns the current record's "payment" value
 * @method integer             getDeduction()          Returns the current record's "deduction" value
 * @method string              getDescription()        Returns the current record's "description" value
 * @method string              getAmount()             Returns the current record's "amount" value
 * @method string              getOvertimeForMonth()   Returns the current record's "overtime_for_month" value
 * @method OhrmTerminationDues setId()                 Sets the current record's "id" value
 * @method OhrmTerminationDues setTerminationId()      Sets the current record's "termination_id" value
 * @method OhrmTerminationDues setEmpNo()              Sets the current record's "emp_no" value
 * @method OhrmTerminationDues setPayment()            Sets the current record's "payment" value
 * @method OhrmTerminationDues setDeduction()          Sets the current record's "deduction" value
 * @method OhrmTerminationDues setDescription()        Sets the current record's "description" value
 * @method OhrmTerminationDues setAmount()             Sets the current record's "amount" value
 * @method OhrmTerminationDues setOvertimeForMonth()   Sets the current record's "overtime_for_month" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmTerminationDues extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_termination_dues');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('termination_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('emp_no', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('payment', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('deduction', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('amount', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('overtime_for_month', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}