<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('HsHrEmpLocations', 'doctrine');

/**
 * BaseHsHrEmpLocations
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $emp_number
 * @property integer $location_id
 * @property OhrmLocation $OhrmLocation
 * @property HsHrEmployee $HsHrEmployee
 * 
 * @method integer          getEmpNumber()    Returns the current record's "emp_number" value
 * @method integer          getLocationId()   Returns the current record's "location_id" value
 * @method OhrmLocation     getOhrmLocation() Returns the current record's "OhrmLocation" value
 * @method HsHrEmployee     getHsHrEmployee() Returns the current record's "HsHrEmployee" value
 * @method HsHrEmpLocations setEmpNumber()    Sets the current record's "emp_number" value
 * @method HsHrEmpLocations setLocationId()   Sets the current record's "location_id" value
 * @method HsHrEmpLocations setOhrmLocation() Sets the current record's "OhrmLocation" value
 * @method HsHrEmpLocations setHsHrEmployee() Sets the current record's "HsHrEmployee" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHsHrEmpLocations extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_emp_locations');
        $this->hasColumn('emp_number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('location_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OhrmLocation', array(
             'local' => 'location_id',
             'foreign' => 'id'));

        $this->hasOne('HsHrEmployee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));
    }
}