<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmLoanrepaymentSchedule', 'doctrine');

/**
 * BaseOhrmLoanrepaymentSchedule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $loanacct
 * @property decimal $mp
 * @property decimal $paid
 * @property date $date
 * @property decimal $balance
 * 
 * @method integer                   getId()       Returns the current record's "id" value
 * @method integer                   getLoanacct() Returns the current record's "loanacct" value
 * @method decimal                   getMp()       Returns the current record's "mp" value
 * @method decimal                   getPaid()     Returns the current record's "paid" value
 * @method date                      getDate()     Returns the current record's "date" value
 * @method decimal                   getBalance()  Returns the current record's "balance" value
 * @method OhrmLoanrepaymentSchedule setId()       Sets the current record's "id" value
 * @method OhrmLoanrepaymentSchedule setLoanacct() Sets the current record's "loanacct" value
 * @method OhrmLoanrepaymentSchedule setMp()       Sets the current record's "mp" value
 * @method OhrmLoanrepaymentSchedule setPaid()     Sets the current record's "paid" value
 * @method OhrmLoanrepaymentSchedule setDate()     Sets the current record's "date" value
 * @method OhrmLoanrepaymentSchedule setBalance()  Sets the current record's "balance" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmLoanrepaymentSchedule extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_loanrepayment_schedule');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('loanacct', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('mp', 'decimal', 10, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             'scale' => '2',
             ));
        $this->hasColumn('paid', 'decimal', 10, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             'scale' => '2',
             ));
        $this->hasColumn('date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('balance', 'decimal', 10, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             'scale' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}