<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmEmploymentStatus', 'doctrine');

/**
 * BaseOhrmEmploymentStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $HsHrEmployee
 * @property Doctrine_Collection $HsHrJobtitEmpstat
 * 
 * @method integer              getId()                Returns the current record's "id" value
 * @method string               getName()              Returns the current record's "name" value
 * @method Doctrine_Collection  getHsHrEmployee()      Returns the current record's "HsHrEmployee" collection
 * @method Doctrine_Collection  getHsHrJobtitEmpstat() Returns the current record's "HsHrJobtitEmpstat" collection
 * @method OhrmEmploymentStatus setId()                Sets the current record's "id" value
 * @method OhrmEmploymentStatus setName()              Sets the current record's "name" value
 * @method OhrmEmploymentStatus setHsHrEmployee()      Sets the current record's "HsHrEmployee" collection
 * @method OhrmEmploymentStatus setHsHrJobtitEmpstat() Sets the current record's "HsHrJobtitEmpstat" collection
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmEmploymentStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_employment_status');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 60,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('HsHrEmployee', array(
             'local' => 'id',
             'foreign' => 'emp_status'));

        $this->hasMany('HsHrJobtitEmpstat', array(
             'local' => 'id',
             'foreign' => 'estat_code'));
    }
}