<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmSalaryDeductions', 'doctrine');

/**
 * BaseOhrmSalaryDeductions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property double $percentage
 * @property integer $is_percentage
 * @property integer $insurance_relief
  * @property string $deduction_formula
 * 
 * @method integer              getId()                Returns the current record's "id" value
 * @method string               getName()              Returns the current record's "name" value
 * @method string               getDeductionFormula()              Returns the current record's "name" value
 * @method double               getPercentage()  Returns the current record's "percentage" value
 * @method integer               getIsPercentage()  Returns the current record's "percentage" value
 * @method integer               getInsuranceRelief()  Returns the current record's "percentage" value
 * @method OhrmSalaryDeductions setId()                Sets the current record's "id" value
 * @method OhrmSalaryDeductions setName()              Sets the current record's "name" value
 * @method OhrmSalaryDeductions setPercentage()  Sets the current record's "percentage" value
 * @method OhrmSalaryDeductions setIsPercentage()  Sets the current record's "percentage" value
 * @method OhrmSalaryDeductions setDeductionFormula()  Sets the current record's "percentage" value
 * @method OhrmSalaryDeductions setInsuranceRelief()  Sets the current record's "percentage" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmSalaryDeductions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_salary_deductions');
        
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
			 
			 $this->hasColumn('deduction_formula', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' =>FALSE,
             'autoincrement' => false,
             'length' => 255,
             ));
        
          $this->hasColumn('percentage', 'double',null, array(
             'type' => 'double',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' =>FALSE,
             'autoincrement' => false,
             'length' => '',
             ));
          
          $this->hasColumn('is_percentage', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 1,
             ));
          
          $this->hasColumn('insurance_relief', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 1,
             ));
      
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}