<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Casualhours', 'doctrine');

/**
 * BaseCasualhours
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $emp_id
 * @property string $monthyear
 * @property string $hours
 * @property integer $half
 * 
 * @method integer     getId()        Returns the current record's "id" value
 * @method integer     getEmpId()     Returns the current record's "emp_id" value
 * @method string      getMonthyear() Returns the current record's "monthyear" value
 * @method string      getHours()     Returns the current record's "hours" value
 * @method integer     getHalf()      Returns the current record's "half" value
 * @method Casualhours setId()        Sets the current record's "id" value
 * @method Casualhours setEmpId()     Sets the current record's "emp_id" value
 * @method Casualhours setMonthyear() Sets the current record's "monthyear" value
 * @method Casualhours setHours()     Sets the current record's "hours" value
 * @method Casualhours setHalf()      Sets the current record's "half" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCasualhours extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('casualhours');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('emp_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('monthyear', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('hours', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('half', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}