<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmEmailNotification', 'doctrine');

/**
 * BaseOhrmEmailNotification
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $is_enable
 * @property Doctrine_Collection $OhrmEmailSubscriber
 * 
 * @method integer               getId()                  Returns the current record's "id" value
 * @method string                getName()                Returns the current record's "name" value
 * @method integer               getIsEnable()            Returns the current record's "is_enable" value
 * @method Doctrine_Collection   getOhrmEmailSubscriber() Returns the current record's "OhrmEmailSubscriber" collection
 * @method OhrmEmailNotification setId()                  Sets the current record's "id" value
 * @method OhrmEmailNotification setName()                Sets the current record's "name" value
 * @method OhrmEmailNotification setIsEnable()            Sets the current record's "is_enable" value
 * @method OhrmEmailNotification setOhrmEmailSubscriber() Sets the current record's "OhrmEmailSubscriber" collection
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmEmailNotification extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_email_notification');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('is_enable', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('OhrmEmailSubscriber', array(
             'local' => 'id',
             'foreign' => 'notification_id'));
    }
}