<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserActions', 'doctrine');

/**
 * BaseUserActions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ua_id
 * @property integer $act_id
 * @property integer $id
 * @property string $status
 * 
 * @method integer     getUaId()   Returns the current record's "ua_id" value
 * @method integer     getActId()  Returns the current record's "act_id" value
 * @method integer     getId()     Returns the current record's "id" value
 * @method string      getStatus() Returns the current record's "status" value
 * @method UserActions setUaId()   Sets the current record's "ua_id" value
 * @method UserActions setActId()  Sets the current record's "act_id" value
 * @method UserActions setId()     Sets the current record's "id" value
 * @method UserActions setStatus() Sets the current record's "status" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserActions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_actions');
        $this->hasColumn('ua_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('act_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('status', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}