<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('HsHrConfig', 'doctrine');

/**
 * BaseHsHrConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $key
 * @property string $value
 * 
 * @method string     getKey()   Returns the current record's "key" value
 * @method string     getValue() Returns the current record's "value" value
 * @method HsHrConfig setKey()   Sets the current record's "key" value
 * @method HsHrConfig setValue() Sets the current record's "value" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHsHrConfig extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_config');
        $this->hasColumn('key', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('value', 'string', 512, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 512,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}