<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmOpenidProvider', 'doctrine');

/**
 * BaseOhrmOpenidProvider
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $provider_name
 * @property string $provider_url
 * @property integer $status
 * @property Doctrine_Collection $OhrmAuthProviderExtraDetails
 * @property Doctrine_Collection $OhrmOpenidUserIdentity
 * 
 * @method integer             getId()                           Returns the current record's "id" value
 * @method string              getProviderName()                 Returns the current record's "provider_name" value
 * @method string              getProviderUrl()                  Returns the current record's "provider_url" value
 * @method integer             getStatus()                       Returns the current record's "status" value
 * @method Doctrine_Collection getOhrmAuthProviderExtraDetails() Returns the current record's "OhrmAuthProviderExtraDetails" collection
 * @method Doctrine_Collection getOhrmOpenidUserIdentity()       Returns the current record's "OhrmOpenidUserIdentity" collection
 * @method OhrmOpenidProvider  setId()                           Sets the current record's "id" value
 * @method OhrmOpenidProvider  setProviderName()                 Sets the current record's "provider_name" value
 * @method OhrmOpenidProvider  setProviderUrl()                  Sets the current record's "provider_url" value
 * @method OhrmOpenidProvider  setStatus()                       Sets the current record's "status" value
 * @method OhrmOpenidProvider  setOhrmAuthProviderExtraDetails() Sets the current record's "OhrmAuthProviderExtraDetails" collection
 * @method OhrmOpenidProvider  setOhrmOpenidUserIdentity()       Sets the current record's "OhrmOpenidUserIdentity" collection
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmOpenidProvider extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_openid_provider');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('provider_name', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 40,
             ));
        $this->hasColumn('provider_url', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('OhrmAuthProviderExtraDetails', array(
             'local' => 'id',
             'foreign' => 'provider_id'));

        $this->hasMany('OhrmOpenidUserIdentity', array(
             'local' => 'id',
             'foreign' => 'provider_id'));
    }
}