<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmAvailableGroupField', 'doctrine');

/**
 * BaseOhrmAvailableGroupField
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $report_group_id
 * @property integer $group_field_id
 * @property OhrmGroupField $OhrmGroupField
 * 
 * @method integer                 getReportGroupId()   Returns the current record's "report_group_id" value
 * @method integer                 getGroupFieldId()    Returns the current record's "group_field_id" value
 * @method OhrmGroupField          getOhrmGroupField()  Returns the current record's "OhrmGroupField" value
 * @method OhrmAvailableGroupField setReportGroupId()   Sets the current record's "report_group_id" value
 * @method OhrmAvailableGroupField setGroupFieldId()    Sets the current record's "group_field_id" value
 * @method OhrmAvailableGroupField setOhrmGroupField()  Sets the current record's "OhrmGroupField" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmAvailableGroupField extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_available_group_field');
        $this->hasColumn('report_group_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('group_field_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OhrmGroupField', array(
             'local' => 'group_field_id',
             'foreign' => 'group_field_id'));
    }
}