<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmChargeLoanproduct', 'doctrine');

/**
 * BaseOhrmChargeLoanproduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $charge_id
 * @property integer $loanproduct_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property OhrmLoanCharges $OhrmLoanCharges
 * @property OhrmLoanproducts $OhrmLoanproducts
 * 
 * @method integer               getId()               Returns the current record's "id" value
 * @method integer               getChargeId()         Returns the current record's "charge_id" value
 * @method integer               getLoanproductId()    Returns the current record's "loanproduct_id" value
 * @method timestamp             getCreatedAt()        Returns the current record's "created_at" value
 * @method timestamp             getUpdatedAt()        Returns the current record's "updated_at" value
 * @method OhrmLoanCharges       getOhrmLoanCharges()  Returns the current record's "OhrmLoanCharges" value
 * @method OhrmLoanproducts      getOhrmLoanproducts() Returns the current record's "OhrmLoanproducts" value
 * @method OhrmChargeLoanproduct setId()               Sets the current record's "id" value
 * @method OhrmChargeLoanproduct setChargeId()         Sets the current record's "charge_id" value
 * @method OhrmChargeLoanproduct setLoanproductId()    Sets the current record's "loanproduct_id" value
 * @method OhrmChargeLoanproduct setCreatedAt()        Sets the current record's "created_at" value
 * @method OhrmChargeLoanproduct setUpdatedAt()        Sets the current record's "updated_at" value
 * @method OhrmChargeLoanproduct setOhrmLoanCharges()  Sets the current record's "OhrmLoanCharges" value
 * @method OhrmChargeLoanproduct setOhrmLoanproducts() Sets the current record's "OhrmLoanproducts" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmChargeLoanproduct extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_charge_loanproduct');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('charge_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('loanproduct_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OhrmLoanCharges', array(
             'local' => 'charge_id',
             'foreign' => 'id'));

        $this->hasOne('OhrmLoanproducts', array(
             'local' => 'loanproduct_id',
             'foreign' => 'id'));
    }
}