<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SecondSalaryslip', 'doctrine');

/**
 * BaseSecondSalaryslip
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $deduction
 * 
 * @method integer          getId()        Returns the current record's "id" value
 * @method string           getDeduction() Returns the current record's "deduction" value
 * @method SecondSalaryslip setId()        Sets the current record's "id" value
 * @method SecondSalaryslip setDeduction() Sets the current record's "deduction" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSecondSalaryslip extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('second_salaryslip');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('deduction', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}