<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmFilterField', 'doctrine');

/**
 * BaseOhrmFilterField
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $filter_field_id
 * @property integer $report_group_id
 * @property string $name
 * @property string $where_clause_part
 * @property string $filter_field_widget
 * @property integer $condition_no
 * @property string $required
 * @property OhrmReportGroup $OhrmReportGroup
 * @property Doctrine_Collection $OhrmSelectedFilterField
 * 
 * @method integer             getFilterFieldId()           Returns the current record's "filter_field_id" value
 * @method integer             getReportGroupId()           Returns the current record's "report_group_id" value
 * @method string              getName()                    Returns the current record's "name" value
 * @method string              getWhereClausePart()         Returns the current record's "where_clause_part" value
 * @method string              getFilterFieldWidget()       Returns the current record's "filter_field_widget" value
 * @method integer             getConditionNo()             Returns the current record's "condition_no" value
 * @method string              getRequired()                Returns the current record's "required" value
 * @method OhrmReportGroup     getOhrmReportGroup()         Returns the current record's "OhrmReportGroup" value
 * @method Doctrine_Collection getOhrmSelectedFilterField() Returns the current record's "OhrmSelectedFilterField" collection
 * @method OhrmFilterField     setFilterFieldId()           Sets the current record's "filter_field_id" value
 * @method OhrmFilterField     setReportGroupId()           Sets the current record's "report_group_id" value
 * @method OhrmFilterField     setName()                    Sets the current record's "name" value
 * @method OhrmFilterField     setWhereClausePart()         Sets the current record's "where_clause_part" value
 * @method OhrmFilterField     setFilterFieldWidget()       Sets the current record's "filter_field_widget" value
 * @method OhrmFilterField     setConditionNo()             Sets the current record's "condition_no" value
 * @method OhrmFilterField     setRequired()                Sets the current record's "required" value
 * @method OhrmFilterField     setOhrmReportGroup()         Sets the current record's "OhrmReportGroup" value
 * @method OhrmFilterField     setOhrmSelectedFilterField() Sets the current record's "OhrmSelectedFilterField" collection
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmFilterField extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_filter_field');
        $this->hasColumn('filter_field_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('report_group_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('where_clause_part', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('filter_field_widget', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('condition_no', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('required', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OhrmReportGroup', array(
             'local' => 'report_group_id',
             'foreign' => 'report_group_id'));

        $this->hasMany('OhrmSelectedFilterField', array(
             'local' => 'filter_field_id',
             'foreign' => 'filter_field_id'));
    }
}