<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmLeaveRequestComment', 'doctrine');

/**
 * BaseOhrmLeaveRequestComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $leave_request_id
 * @property timestamp $created
 * @property string $created_by_name
 * @property integer $created_by_id
 * @property integer $created_by_emp_number
 * @property string $comments
 * @property OhrmLeaveRequest $OhrmLeaveRequest
 * @property OhrmUser $OhrmUser
 * @property HsHrEmployee $HsHrEmployee
 * 
 * @method integer                 getId()                    Returns the current record's "id" value
 * @method integer                 getLeaveRequestId()        Returns the current record's "leave_request_id" value
 * @method timestamp               getCreated()               Returns the current record's "created" value
 * @method string                  getCreatedByName()         Returns the current record's "created_by_name" value
 * @method integer                 getCreatedById()           Returns the current record's "created_by_id" value
 * @method integer                 getCreatedByEmpNumber()    Returns the current record's "created_by_emp_number" value
 * @method string                  getComments()              Returns the current record's "comments" value
 * @method OhrmLeaveRequest        getOhrmLeaveRequest()      Returns the current record's "OhrmLeaveRequest" value
 * @method OhrmUser                getOhrmUser()              Returns the current record's "OhrmUser" value
 * @method HsHrEmployee            getHsHrEmployee()          Returns the current record's "HsHrEmployee" value
 * @method OhrmLeaveRequestComment setId()                    Sets the current record's "id" value
 * @method OhrmLeaveRequestComment setLeaveRequestId()        Sets the current record's "leave_request_id" value
 * @method OhrmLeaveRequestComment setCreated()               Sets the current record's "created" value
 * @method OhrmLeaveRequestComment setCreatedByName()         Sets the current record's "created_by_name" value
 * @method OhrmLeaveRequestComment setCreatedById()           Sets the current record's "created_by_id" value
 * @method OhrmLeaveRequestComment setCreatedByEmpNumber()    Sets the current record's "created_by_emp_number" value
 * @method OhrmLeaveRequestComment setComments()              Sets the current record's "comments" value
 * @method OhrmLeaveRequestComment setOhrmLeaveRequest()      Sets the current record's "OhrmLeaveRequest" value
 * @method OhrmLeaveRequestComment setOhrmUser()              Sets the current record's "OhrmUser" value
 * @method OhrmLeaveRequestComment setHsHrEmployee()          Sets the current record's "HsHrEmployee" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmLeaveRequestComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_leave_request_comment');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('leave_request_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_by_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_by_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_by_emp_number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('comments', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OhrmLeaveRequest', array(
             'local' => 'leave_request_id',
             'foreign' => 'id'));

        $this->hasOne('OhrmUser', array(
             'local' => 'created_by_id',
             'foreign' => 'id'));

        $this->hasOne('HsHrEmployee', array(
             'local' => 'created_by_emp_number',
             'foreign' => 'emp_number'));
    }
}