<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ohrm_Bank', 'doctrine');

/**
 * BaseOhrm_Bank
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $bank_code
 * @property string $bank_name
 * 
 * @method integer   getId()        Returns the current record's "id" value
 * @method string    getBankCode()  Returns the current record's "bank_code" value
 * @method string    getBankName()  Returns the current record's "bank_name" value
 * @method Ohrm_Bank setId()        Sets the current record's "id" value
 * @method Ohrm_Bank setBankCode()  Sets the current record's "bank_code" value
 * @method Ohrm_Bank setBankName()  Sets the current record's "bank_name" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrm_Bank extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_Bank');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('bank_code', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('bank_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}