<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmMenuItem', 'doctrine');

/**
 * BaseOhrmMenuItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $menu_title
 * @property integer $screen_id
 * @property integer $parent_id
 * @property integer $level
 * @property integer $order_hint
 * @property string $url_extras
 * @property integer $status
 * @property OhrmScreen $OhrmScreen
 * 
 * @method integer      getId()         Returns the current record's "id" value
 * @method string       getMenuTitle()  Returns the current record's "menu_title" value
 * @method integer      getScreenId()   Returns the current record's "screen_id" value
 * @method integer      getParentId()   Returns the current record's "parent_id" value
 * @method integer      getLevel()      Returns the current record's "level" value
 * @method integer      getOrderHint()  Returns the current record's "order_hint" value
 * @method string       getUrlExtras()  Returns the current record's "url_extras" value
 * @method integer      getStatus()     Returns the current record's "status" value
 * @method OhrmScreen   getOhrmScreen() Returns the current record's "OhrmScreen" value
 * @method OhrmMenuItem setId()         Sets the current record's "id" value
 * @method OhrmMenuItem setMenuTitle()  Sets the current record's "menu_title" value
 * @method OhrmMenuItem setScreenId()   Sets the current record's "screen_id" value
 * @method OhrmMenuItem setParentId()   Sets the current record's "parent_id" value
 * @method OhrmMenuItem setLevel()      Sets the current record's "level" value
 * @method OhrmMenuItem setOrderHint()  Sets the current record's "order_hint" value
 * @method OhrmMenuItem setUrlExtras()  Sets the current record's "url_extras" value
 * @method OhrmMenuItem setStatus()     Sets the current record's "status" value
 * @method OhrmMenuItem setOhrmScreen() Sets the current record's "OhrmScreen" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmMenuItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_menu_item');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('menu_title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('screen_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('parent_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('level', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('order_hint', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('url_extras', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OhrmScreen', array(
             'local' => 'screen_id',
             'foreign' => 'id'));
    }
}