<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmEarnings', 'doctrine');

/**
 * BaseOhrmEarnings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $taxable
 * @property integer $is_recurring
 * @property double $tax_percentage
 * @property integer $active
 * 
 * @method integer      getId()           Returns the current record's "id" value
 * @method string       getName()         Returns the current record's "name" value
 * @method integer      getTaxable()      Returns the current record's "taxable" value
 * @method integer      getTaxPercentage()      Returns the current record's "taxable" value
 * @method integer      getIsRecurring()  Returns the current record's "is_recurring" value
 * @method integer      getActive()       Returns the current record's "active" value
 * @method OhrmEarnings setId()           Sets the current record's "id" value
 * @method OhrmEarnings setName()         Sets the current record's "name" value
 * @method OhrmEarnings setTaxable()      Sets the current record's "taxable" value
 * @method OhrmEarnings setIsRecurring()  Sets the current record's "is_recurring" value
 * @method OhrmEarnings setTaxPercentage()  Sets the current record's "is_recurring" value
 * @method OhrmEarnings setActive()       Sets the current record's "active" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmEarnings extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_earnings');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('taxable', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('is_recurring', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('tax_percentage', 'double', null, array(
             'type' => 'double',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}