<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('HsHrCustomImport', 'doctrine');

/**
 * BaseHsHrCustomImport
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $import_id
 * @property string $name
 * @property string $fields
 * @property integer $has_heading
 * 
 * @method integer          getImportId()    Returns the current record's "import_id" value
 * @method string           getName()        Returns the current record's "name" value
 * @method string           getFields()      Returns the current record's "fields" value
 * @method integer          getHasHeading()  Returns the current record's "has_heading" value
 * @method HsHrCustomImport setImportId()    Sets the current record's "import_id" value
 * @method HsHrCustomImport setName()        Sets the current record's "name" value
 * @method HsHrCustomImport setFields()      Sets the current record's "fields" value
 * @method HsHrCustomImport setHasHeading()  Sets the current record's "has_heading" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHsHrCustomImport extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_custom_import');
        $this->hasColumn('import_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('fields', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('has_heading', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}