<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmSelectedDisplayFieldGroup', 'doctrine');

/**
 * BaseOhrmSelectedDisplayFieldGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $report_id
 * @property integer $display_field_group_id
 * @property OhrmReport $OhrmReport
 * @property OhrmDisplayFieldGroup $OhrmDisplayFieldGroup
 * 
 * @method integer                       getId()                     Returns the current record's "id" value
 * @method integer                       getReportId()               Returns the current record's "report_id" value
 * @method integer                       getDisplayFieldGroupId()    Returns the current record's "display_field_group_id" value
 * @method OhrmReport                    getOhrmReport()             Returns the current record's "OhrmReport" value
 * @method OhrmDisplayFieldGroup         getOhrmDisplayFieldGroup()  Returns the current record's "OhrmDisplayFieldGroup" value
 * @method OhrmSelectedDisplayFieldGroup setId()                     Sets the current record's "id" value
 * @method OhrmSelectedDisplayFieldGroup setReportId()               Sets the current record's "report_id" value
 * @method OhrmSelectedDisplayFieldGroup setDisplayFieldGroupId()    Sets the current record's "display_field_group_id" value
 * @method OhrmSelectedDisplayFieldGroup setOhrmReport()             Sets the current record's "OhrmReport" value
 * @method OhrmSelectedDisplayFieldGroup setOhrmDisplayFieldGroup()  Sets the current record's "OhrmDisplayFieldGroup" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmSelectedDisplayFieldGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_selected_display_field_group');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('report_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('display_field_group_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OhrmReport', array(
             'local' => 'report_id',
             'foreign' => 'report_id'));

        $this->hasOne('OhrmDisplayFieldGroup', array(
             'local' => 'display_field_group_id',
             'foreign' => 'id'));
    }
}