<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Salaryslipdata', 'doctrine');

/**
 * BaseSalaryslipdata
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $metavalue
 * @property integer $emp_id
 * @property string $month
 * @property string $year
 * @property timestamp $time
 * 
 * @method integer        getId()        Returns the current record's "id" value
 * @method string         getMetavalue() Returns the current record's "metavalue" value
 * @method integer        getEmpId()     Returns the current record's "emp_id" value
 * @method string         getMonth()     Returns the current record's "month" value
 * @method string         getYear()      Returns the current record's "year" value
 * @method timestamp      getTime()      Returns the current record's "time" value
 * @method Salaryslipdata setId()        Sets the current record's "id" value
 * @method Salaryslipdata setMetavalue() Sets the current record's "metavalue" value
 * @method Salaryslipdata setEmpId()     Sets the current record's "emp_id" value
 * @method Salaryslipdata setMonth()     Sets the current record's "month" value
 * @method Salaryslipdata setYear()      Sets the current record's "year" value
 * @method Salaryslipdata setTime()      Sets the current record's "time" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSalaryslipdata extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('salaryslipdata');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('metavalue', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('emp_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('month', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('year', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('time', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}