<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmTrainingCourses', 'doctrine');

/**
 * BaseOhrmTrainingCourses
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $course_title
 * @property integer $subunit
 * @property string $coordinator
 * @property string $cost
 * @property string $status
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getCourseTitle()  Returns the current record's "course_title" value
 * @method integer             getSubunit()      Returns the current record's "subunit" value
 * @method string              getCoordinator()  Returns the current record's "coordinator" value
 * @method string              getCost()         Returns the current record's "cost" value
 * @method string              getStatus()       Returns the current record's "status" value
 * @method OhrmTrainingCourses setId()           Sets the current record's "id" value
 * @method OhrmTrainingCourses setCourseTitle()  Sets the current record's "course_title" value
 * @method OhrmTrainingCourses setSubunit()      Sets the current record's "subunit" value
 * @method OhrmTrainingCourses setCoordinator()  Sets the current record's "coordinator" value
 * @method OhrmTrainingCourses setCost()         Sets the current record's "cost" value
 * @method OhrmTrainingCourses setStatus()       Sets the current record's "status" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmTrainingCourses extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_training_courses');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('course_title', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('subunit', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('coordinator', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('cost', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('status', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}