<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('HsHrEmpWorkExperience', 'doctrine');

/**
 * BaseHsHrEmpWorkExperience
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $emp_number
 * @property decimal $eexp_seqno
 * @property string $eexp_employer
 * @property string $eexp_jobtit
 * @property timestamp $eexp_from_date
 * @property timestamp $eexp_to_date
 * @property string $eexp_comments
 * @property integer $eexp_internal
 * @property HsHrEmployee $HsHrEmployee
 * 
 * @method integer               getEmpNumber()      Returns the current record's "emp_number" value
 * @method decimal               getEexpSeqno()      Returns the current record's "eexp_seqno" value
 * @method string                getEexpEmployer()   Returns the current record's "eexp_employer" value
 * @method string                getEexpJobtit()     Returns the current record's "eexp_jobtit" value
 * @method timestamp             getEexpFromDate()   Returns the current record's "eexp_from_date" value
 * @method timestamp             getEexpToDate()     Returns the current record's "eexp_to_date" value
 * @method string                getEexpComments()   Returns the current record's "eexp_comments" value
 * @method integer               getEexpInternal()   Returns the current record's "eexp_internal" value
 * @method HsHrEmployee          getHsHrEmployee()   Returns the current record's "HsHrEmployee" value
 * @method HsHrEmpWorkExperience setEmpNumber()      Sets the current record's "emp_number" value
 * @method HsHrEmpWorkExperience setEexpSeqno()      Sets the current record's "eexp_seqno" value
 * @method HsHrEmpWorkExperience setEexpEmployer()   Sets the current record's "eexp_employer" value
 * @method HsHrEmpWorkExperience setEexpJobtit()     Sets the current record's "eexp_jobtit" value
 * @method HsHrEmpWorkExperience setEexpFromDate()   Sets the current record's "eexp_from_date" value
 * @method HsHrEmpWorkExperience setEexpToDate()     Sets the current record's "eexp_to_date" value
 * @method HsHrEmpWorkExperience setEexpComments()   Sets the current record's "eexp_comments" value
 * @method HsHrEmpWorkExperience setEexpInternal()   Sets the current record's "eexp_internal" value
 * @method HsHrEmpWorkExperience setHsHrEmployee()   Sets the current record's "HsHrEmployee" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHsHrEmpWorkExperience extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_emp_work_experience');
        $this->hasColumn('emp_number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('eexp_seqno', 'decimal', 10, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('eexp_employer', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('eexp_jobtit', 'string', 120, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 120,
             ));
        $this->hasColumn('eexp_from_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('eexp_to_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('eexp_comments', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('eexp_internal', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('HsHrEmployee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));
    }
}