<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmEmpTerminationReason', 'doctrine');

/**
 * BaseOhrmEmpTerminationReason
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $OhrmEmpTermination
 * 
 * @method integer                  getId()                 Returns the current record's "id" value
 * @method string                   getName()               Returns the current record's "name" value
 * @method Doctrine_Collection      getOhrmEmpTermination() Returns the current record's "OhrmEmpTermination" collection
 * @method OhrmEmpTerminationReason setId()                 Sets the current record's "id" value
 * @method OhrmEmpTerminationReason setName()               Sets the current record's "name" value
 * @method OhrmEmpTerminationReason setOhrmEmpTermination() Sets the current record's "OhrmEmpTermination" collection
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmEmpTerminationReason extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_emp_termination_reason');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('OhrmEmpTermination', array(
             'local' => 'id',
             'foreign' => 'reason_id'));
    }
}