<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmWorkShift', 'doctrine');

/**
 * BaseOhrmWorkShift
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property decimal $hours_per_day
 * @property time $start_time
 * @property time $end_time
 * @property Doctrine_Collection $OhrmEmployeeWorkShift
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method string              getName()                  Returns the current record's "name" value
 * @method decimal             getHoursPerDay()           Returns the current record's "hours_per_day" value
 * @method time                getStartTime()             Returns the current record's "start_time" value
 * @method time                getEndTime()               Returns the current record's "end_time" value
 * @method Doctrine_Collection getOhrmEmployeeWorkShift() Returns the current record's "OhrmEmployeeWorkShift" collection
 * @method OhrmWorkShift       setId()                    Sets the current record's "id" value
 * @method OhrmWorkShift       setName()                  Sets the current record's "name" value
 * @method OhrmWorkShift       setHoursPerDay()           Sets the current record's "hours_per_day" value
 * @method OhrmWorkShift       setStartTime()             Sets the current record's "start_time" value
 * @method OhrmWorkShift       setEndTime()               Sets the current record's "end_time" value
 * @method OhrmWorkShift       setOhrmEmployeeWorkShift() Sets the current record's "OhrmEmployeeWorkShift" collection
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmWorkShift extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_work_shift');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('hours_per_day', 'decimal', 4, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             'scale' => '2',
             ));
        $this->hasColumn('start_time', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('end_time', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('OhrmEmployeeWorkShift', array(
             'local' => 'id',
             'foreign' => 'work_shift_id'));
    }
}