<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmUserSelectionRule', 'doctrine');

/**
 * BaseOhrmUserSelectionRule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $implementation_class
 * @property string $rule_xml_data
 * 
 * @method integer               getId()                   Returns the current record's "id" value
 * @method string                getName()                 Returns the current record's "name" value
 * @method string                getDescription()          Returns the current record's "description" value
 * @method string                getImplementationClass()  Returns the current record's "implementation_class" value
 * @method string                getRuleXmlData()          Returns the current record's "rule_xml_data" value
 * @method OhrmUserSelectionRule setId()                   Sets the current record's "id" value
 * @method OhrmUserSelectionRule setName()                 Sets the current record's "name" value
 * @method OhrmUserSelectionRule setDescription()          Sets the current record's "description" value
 * @method OhrmUserSelectionRule setImplementationClass()  Sets the current record's "implementation_class" value
 * @method OhrmUserSelectionRule setRuleXmlData()          Sets the current record's "rule_xml_data" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmUserSelectionRule extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_user_selection_rule');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('implementation_class', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('rule_xml_data', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}