<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('HsHrEmployee', 'doctrine');

/**
 * BaseHsHrEmployee
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $emp_number
 * @property string $employee_id
 * @property string $emp_lastname
 * @property string $emp_firstname
 * @property string $emp_middle_name
 * @property string $emp_nick_name
 * @property integer $emp_pensionable
 * @property integer $pay_nssf
 * @property integer $pay_nhif
 * @property integer $pay_tax
 * @property integer $pay_relief
 * @property string $fixed_tax
 * @property integer $encash_leave
 * @property string $vehicle_type
 * @property string $vehicle_value
 * @property string $vehicle_benefit
 * @property string $ethnic_race_code
 * @property date $emp_birthday
 * @property integer $nation_code
 * @property integer $emp_gender
 * @property string $emp_marital_status
 * @property string $emp_ssn_num
 * @property string $emp_sin_num
 * @property string $emp_other_id
 * @property string $emp_dri_lice_num
 * @property date $emp_dri_lice_exp_date
 * @property string $emp_military_service
 * @property integer $emp_status
 * @property integer $job_title_code
 * @property integer $eeo_cat_code
 * @property integer $work_station
 * @property string $emp_street1
 * @property string $emp_street2
 * @property string $city_code
 * @property string $coun_code
 * @property string $provin_code
 * @property string $emp_zipcode
 * @property string $emp_hm_telephone
 * @property string $vehicle_type
 * @property string $vehicle_benefit
 * @property string $vehicle_value
 * @property string $emp_mobile
 * @property string $emp_work_telephone
 * @property string $emp_work_email
 * @property string $sal_grd_code
 * @property date $joined_date
 * @property string $emp_oth_email
 * @property integer $termination_id
 * @property integer $on_probation
 * @property string $custom1
 * @property string $custom2
 * @property string $custom3
 * @property string $custom4
 * @property string $custom5
 * @property string $custom6
 * @property string $custom7
 * @property string $custom8
 * @property string $custom9
 * @property string $custom10
 * @property string $phototype
 * @property string $photo
 * @property string $fingerprint
 * @property string $fingerprintype
 * @property string $regtemp
 * @property OhrmSubunit $OhrmSubunit
 * @property OhrmNationality $OhrmNationality
 * @property OhrmJobTitle $OhrmJobTitle
 * @property OhrmEmploymentStatus $OhrmEmploymentStatus
 * @property OhrmJobCategory $OhrmJobCategory
 * @property OhrmEmpTermination $OhrmEmpTermination
 * @property Doctrine_Collection $HsHrEmpAttachment
 * @property Doctrine_Collection $HsHrEmpBasicsalary
 * @property Doctrine_Collection $HsHrEmpChildren
 * 
 * @method integer              getEmpNumber()             Returns the current record's "emp_number" value
 * @method string               getEmployeeId()            Returns the current record's "employee_id" value
 * @method string               getEmpLastname()           Returns the current record's "emp_lastname" value
 * @method string               getEmpFirstname()          Returns the current record's "emp_firstname" value
 * @method string               getEmpMiddleName()         Returns the current record's "emp_middle_name" value
 * @method string               getEmpNickName()           Returns the current record's "emp_nick_name" value
 * @method integer              getEmpPensionable()        Returns the current record's "emp_pensionable" value
 * @method integer              getPayNssf()               Returns the current record's "pay_nssf" value
 * @method integer              getPayNhif()               Returns the current record's "pay_nhif" value
 * @method integer              getPayTax()                Returns the current record's "pay_tax" value
 * @method integer              getPayRelief()             Returns the current record's "pay_relief" value
 * @method string               getFixedTax()              Returns the current record's "fixed_tax" value
 * @method integer              getEncashLeave()           Returns the current record's "encash_leave" value
 * @method string               getVehicleType()           Returns the current record's "vehicle_type" value
 * @method string               getVehicleValue()          Returns the current record's "vehicle_value" value
 * @method string               getVehicleBenefit()        Returns the current record's "vehicle_benefit" value
 * @method string               getEthnicRaceCode()        Returns the current record's "ethnic_race_code" value
 * @method date                 getEmpBirthday()           Returns the current record's "emp_birthday" value
 * @method integer              getNationCode()            Returns the current record's "nation_code" value
 * @method integer              getEmpGender()             Returns the current record's "emp_gender" value
 * @method string               getEmpMaritalStatus()      Returns the current record's "emp_marital_status" value
 * @method string               getEmpSsnNum()             Returns the current record's "emp_ssn_num" value
 * @method string               getEmpSinNum()             Returns the current record's "emp_sin_num" value
 * @method string               getEmpOtherId()            Returns the current record's "emp_other_id" value
 * @method string               getEmpDriLiceNum()         Returns the current record's "emp_dri_lice_num" value
 * @method date                 getEmpDriLiceExpDate()     Returns the current record's "emp_dri_lice_exp_date" value
 * @method string               getEmpMilitaryService()    Returns the current record's "emp_military_service" value
 * @method integer              getEmpStatus()             Returns the current record's "emp_status" value
 * @method integer              getJobTitleCode()          Returns the current record's "job_title_code" value
 * @method integer              getEeoCatCode()            Returns the current record's "eeo_cat_code" value
 * @method integer              getWorkStation()           Returns the current record's "work_station" value
 * @method string               getEmpStreet1()            Returns the current record's "emp_street1" value
 * @method string               getEmpStreet2()            Returns the current record's "emp_street2" value
 * @method string               getCityCode()              Returns the current record's "city_code" value
 * @method string               getCounCode()              Returns the current record's "coun_code" value
 * @method string               getProvinCode()            Returns the current record's "provin_code" value
 * @method string               getEmpZipcode()            Returns the current record's "emp_zipcode" value
 * @method string               getEmpHmTelephone()        Returns the current record's "emp_hm_telephone" value
 * @method string               getEmpMobile()             Returns the current record's "emp_mobile" value
 * @method string               getEmpWorkTelephone()      Returns the current record's "emp_work_telephone" value
 * @method string               getEmpWorkEmail()          Returns the current record's "emp_work_email" value
 * @method string               getSalGrdCode()            Returns the current record's "sal_grd_code" value
 * @method date                 getJoinedDate()            Returns the current record's "joined_date" value
 * @method string               getEmpOthEmail()           Returns the current record's "emp_oth_email" value
 * @method integer              getTerminationId()         Returns the current record's "termination_id" value
 * @method integer              getOnProbation()           Returns the current record's "on_probation" value
 * @method string               getCustom1()               Returns the current record's "custom1" value
 * @method string               getCustom2()               Returns the current record's "custom2" value
 * @method string               getCustom3()               Returns the current record's "custom3" value
 * @method string               getCustom4()               Returns the current record's "custom4" value
 * @method string               getCustom5()               Returns the current record's "custom5" value
 * @method string               getCustom6()               Returns the current record's "custom6" value
 * @method string               getCustom7()               Returns the current record's "custom7" value
 * @method string               getCustom8()               Returns the current record's "custom8" value
 * @method string               getCustom9()               Returns the current record's "custom9" value
 * @method string               getCustom10()              Returns the current record's "custom10" value
 * @method string               getPhototype()             Returns the current record's "phototype" value
 * @method string               getPhoto()                 Returns the current record's "photo" value
 * @method string               getFingerprint()           Returns the current record's "fingerprint" value
 * @method string               getFingerprintype()        Returns the current record's "fingerprintype" value
 * @method string               getRegtemp()               Returns the current record's "regtemp" value
 * @method OhrmSubunit          getOhrmSubunit()           Returns the current record's "OhrmSubunit" value
 * @method OhrmNationality      getOhrmNationality()       Returns the current record's "OhrmNationality" value
 * @method OhrmJobTitle         getOhrmJobTitle()          Returns the current record's "OhrmJobTitle" value
 * @method OhrmEmploymentStatus getOhrmEmploymentStatus()  Returns the current record's "OhrmEmploymentStatus" value
 * @method OhrmJobCategory      getOhrmJobCategory()       Returns the current record's "OhrmJobCategory" value
 * @method OhrmEmpTermination   getOhrmEmpTermination()    Returns the current record's "OhrmEmpTermination" value
 * @method Doctrine_Collection  getHsHrEmpAttachment()     Returns the current record's "HsHrEmpAttachment" collection
 * @method Doctrine_Collection  getHsHrEmpBasicsalary()    Returns the current record's "HsHrEmpBasicsalary" collection
 * @method Doctrine_Collection  getHsHrEmpChildren()       Returns the current record's "HsHrEmpChildren" collection
 * @method HsHrEmployee         setEmpNumber()             Sets the current record's "emp_number" value
 * @method HsHrEmployee         setEmployeeId()            Sets the current record's "employee_id" value
 * @method HsHrEmployee         setEmpLastname()           Sets the current record's "emp_lastname" value
 * @method HsHrEmployee         setEmpFirstname()          Sets the current record's "emp_firstname" value
 * @method HsHrEmployee         setEmpMiddleName()         Sets the current record's "emp_middle_name" value
 * @method HsHrEmployee         setEmpNickName()           Sets the current record's "emp_nick_name" value
 * @method HsHrEmployee         setEmpPensionable()        Sets the current record's "emp_pensionable" value
 * @method HsHrEmployee         setPayNssf()               Sets the current record's "pay_nssf" value
 * @method HsHrEmployee         setPayNhif()               Sets the current record's "pay_nhif" value
 * @method HsHrEmployee         setPayTax()                Sets the current record's "pay_tax" value
 * @method HsHrEmployee         setPayRelief()             Sets the current record's "pay_relief" value
 * @method HsHrEmployee         setFixedTax()              Sets the current record's "fixed_tax" value
 * @method HsHrEmployee         setEncashLeave()           Sets the current record's "encash_leave" value
 * @method HsHrEmployee         setVehicleType()           Sets the current record's "vehicle_type" value
 * @method HsHrEmployee         setVehicleValue()          Sets the current record's "vehicle_value" value
 * @method HsHrEmployee         setVehicleBenefit()        Sets the current record's "vehicle_benefit" value
 * @method HsHrEmployee         setEthnicRaceCode()        Sets the current record's "ethnic_race_code" value
 * @method HsHrEmployee         setEmpBirthday()           Sets the current record's "emp_birthday" value
 * @method HsHrEmployee         setNationCode()            Sets the current record's "nation_code" value
 * @method HsHrEmployee         setEmpGender()             Sets the current record's "emp_gender" value
 * @method HsHrEmployee         setEmpMaritalStatus()      Sets the current record's "emp_marital_status" value
 * @method HsHrEmployee         setEmpSsnNum()             Sets the current record's "emp_ssn_num" value
 * @method HsHrEmployee         setEmpSinNum()             Sets the current record's "emp_sin_num" value
 * @method HsHrEmployee         setEmpOtherId()            Sets the current record's "emp_other_id" value
 * @method HsHrEmployee         setEmpDriLiceNum()         Sets the current record's "emp_dri_lice_num" value
 * @method HsHrEmployee         setEmpDriLiceExpDate()     Sets the current record's "emp_dri_lice_exp_date" value
 * @method HsHrEmployee         setEmpMilitaryService()    Sets the current record's "emp_military_service" value
 * @method HsHrEmployee         setEmpStatus()             Sets the current record's "emp_status" value
 * @method HsHrEmployee         setJobTitleCode()          Sets the current record's "job_title_code" value
 * @method HsHrEmployee         setEeoCatCode()            Sets the current record's "eeo_cat_code" value
 * @method HsHrEmployee         setWorkStation()           Sets the current record's "work_station" value
 * @method HsHrEmployee         setEmpStreet1()            Sets the current record's "emp_street1" value
 * @method HsHrEmployee         setEmpStreet2()            Sets the current record's "emp_street2" value
 * @method HsHrEmployee         setCityCode()              Sets the current record's "city_code" value
 * @method HsHrEmployee         setCounCode()              Sets the current record's "coun_code" value
 * @method HsHrEmployee         setProvinCode()            Sets the current record's "provin_code" value
 * @method HsHrEmployee         setEmpZipcode()            Sets the current record's "emp_zipcode" value
 * @method HsHrEmployee         setEmpHmTelephone()        Sets the current record's "emp_hm_telephone" value
 * @method HsHrEmployee         setEmpMobile()             Sets the current record's "emp_mobile" value
 * @method HsHrEmployee         setEmpWorkTelephone()      Sets the current record's "emp_work_telephone" value
 * @method HsHrEmployee         setEmpWorkEmail()          Sets the current record's "emp_work_email" value
 * @method HsHrEmployee         setSalGrdCode()            Sets the current record's "sal_grd_code" value
 * @method HsHrEmployee         setJoinedDate()            Sets the current record's "joined_date" value
 * @method HsHrEmployee         setEmpOthEmail()           Sets the current record's "emp_oth_email" value
 * @method HsHrEmployee         setTerminationId()         Sets the current record's "termination_id" value
 * @method HsHrEmployee         setOnProbation()           Sets the current record's "on_probation" value
 * @method HsHrEmployee         setCustom1()               Sets the current record's "custom1" value
 * @method HsHrEmployee         setCustom2()               Sets the current record's "custom2" value
 * @method HsHrEmployee         setCustom3()               Sets the current record's "custom3" value
 * @method HsHrEmployee         setCustom4()               Sets the current record's "custom4" value
 * @method HsHrEmployee         setCustom5()               Sets the current record's "custom5" value
 * @method HsHrEmployee         setCustom6()               Sets the current record's "custom6" value
 * @method HsHrEmployee         setCustom7()               Sets the current record's "custom7" value
 * @method HsHrEmployee         setCustom8()               Sets the current record's "custom8" value
 * @method HsHrEmployee         setCustom9()               Sets the current record's "custom9" value
 * @method HsHrEmployee         setCustom10()              Sets the current record's "custom10" value
 * @method HsHrEmployee         setPhototype()             Sets the current record's "phototype" value
 * @method HsHrEmployee         setPhoto()                 Sets the current record's "photo" value
 * @method HsHrEmployee         setFingerprint()           Sets the current record's "fingerprint" value
   * @method HsHrEmployee         setFingerprintype()        Sets the current record's "fingerprintype" value
 * @method HsHrEmployee         setRegtemp()               Sets the current record's "regtemp" value
 * @method HsHrEmployee         setOhrmSubunit()           Sets the current record's "OhrmSubunit" value
 * @method HsHrEmployee         setOhrmNationality()       Sets the current record's "OhrmNationality" value
 * @method HsHrEmployee         setOhrmJobTitle()          Sets the current record's "OhrmJobTitle" value
 * @method HsHrEmployee         setOhrmEmploymentStatus()  Sets the current record's "OhrmEmploymentStatus" value
 * @method HsHrEmployee         setOhrmJobCategory()       Sets the current record's "OhrmJobCategory" value
 * @method HsHrEmployee         setOhrmEmpTermination()    Sets the current record's "OhrmEmpTermination" value
 * @method HsHrEmployee         setHsHrEmpAttachment()     Sets the current record's "HsHrEmpAttachment" collection
 * @method HsHrEmployee         setHsHrEmpBasicsalary()    Sets the current record's "HsHrEmpBasicsalary" collection
 * @method HsHrEmployee         setHsHrEmpChildren()       Sets the current record's "HsHrEmpChildren" collection
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHsHrEmployee extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_employee');
        $this->hasColumn('emp_number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('employee_id', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('emp_lastname', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('emp_firstname', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('emp_middle_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('emp_nick_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('emp_pensionable', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('pay_nssf', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('pay_nhif', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('pay_tax', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('pay_relief', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('fixed_tax', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('encash_leave', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('vehicle_type', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('vehicle_value', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('vehicle_benefit', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('ethnic_race_code', 'string', 13, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 13,
             ));
        $this->hasColumn('emp_birthday', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('nation_code', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('emp_gender', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('emp_marital_status', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('emp_ssn_num', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('emp_sin_num', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('emp_other_id', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('emp_dri_lice_num', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('emp_dri_lice_exp_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('emp_military_service', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('emp_status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('job_title_code', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('eeo_cat_code', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('work_station', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('emp_street1', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('emp_street2', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('city_code', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('coun_code', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('provin_code', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('emp_zipcode', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('emp_hm_telephone', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('emp_mobile', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('emp_work_telephone', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('emp_work_email', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('sal_grd_code', 'string', 13, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 13,
             ));
        $this->hasColumn('joined_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('emp_oth_email', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('termination_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('on_probation', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('custom1', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('custom2', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('custom3', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('custom4', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('custom5', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('custom6', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('custom7', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('custom8', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('custom9', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('custom10', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('phototype', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('photo', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('fingerprint', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('fingerprintype', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('regtemp', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        
         $this->hasColumn('vehicle_benefit', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
          $this->hasColumn('vehicle_value', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
           $this->hasColumn('vehicle_type', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OhrmSubunit', array(
             'local' => 'work_station',
             'foreign' => 'id'));

        $this->hasOne('OhrmNationality', array(
             'local' => 'nation_code',
             'foreign' => 'id'));

        $this->hasOne('OhrmJobTitle', array(
             'local' => 'job_title_code',
             'foreign' => 'id'));

        $this->hasOne('OhrmEmploymentStatus', array(
             'local' => 'emp_status',
             'foreign' => 'id'));

        $this->hasOne('OhrmJobCategory', array(
             'local' => 'eeo_cat_code',
             'foreign' => 'id'));

        $this->hasOne('OhrmEmpTermination', array(
             'local' => 'termination_id',
             'foreign' => 'id'));

        $this->hasMany('HsHrEmpAttachment', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('HsHrEmpBasicsalary', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('HsHrEmpChildren', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));
    }
}