<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('HsHrCustomExport', 'doctrine');

/**
 * BaseHsHrCustomExport
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $export_id
 * @property string $name
 * @property string $fields
 * @property string $headings
 * 
 * @method integer          getExportId()  Returns the current record's "export_id" value
 * @method string           getName()      Returns the current record's "name" value
 * @method string           getFields()    Returns the current record's "fields" value
 * @method string           getHeadings()  Returns the current record's "headings" value
 * @method HsHrCustomExport setExportId()  Sets the current record's "export_id" value
 * @method HsHrCustomExport setName()      Sets the current record's "name" value
 * @method HsHrCustomExport setFields()    Sets the current record's "fields" value
 * @method HsHrCustomExport setHeadings()  Sets the current record's "headings" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHsHrCustomExport extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_custom_export');
        $this->hasColumn('export_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('fields', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('headings', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}