<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmTrainingSession', 'doctrine');

/**
 * BaseOhrmTrainingSession
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $date
 * @property string $project
 * @property string $trainer
 * @property integer $course
 * @property string $status
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method string              getTitle()   Returns the current record's "title" value
 * @method string              getDate()    Returns the current record's "date" value
 * @method string              getProject() Returns the current record's "project" value
 * @method string              getTrainer() Returns the current record's "trainer" value
 * @method integer             getCourse()  Returns the current record's "course" value
 * @method string              getStatus()  Returns the current record's "status" value
 * @method OhrmTrainingSession setId()      Sets the current record's "id" value
 * @method OhrmTrainingSession setTitle()   Sets the current record's "title" value
 * @method OhrmTrainingSession setDate()    Sets the current record's "date" value
 * @method OhrmTrainingSession setProject() Sets the current record's "project" value
 * @method OhrmTrainingSession setTrainer() Sets the current record's "trainer" value
 * @method OhrmTrainingSession setCourse()  Sets the current record's "course" value
 * @method OhrmTrainingSession setStatus()  Sets the current record's "status" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmTrainingSession extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_training_session');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('date', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('project', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('trainer', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('course', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('status', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}