<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmSelectedDisplayField', 'doctrine');

/**
 * BaseOhrmSelectedDisplayField
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $display_field_id
 * @property integer $report_id
 * @property OhrmReport $OhrmReport
 * @property OhrmDisplayField $OhrmDisplayField
 * 
 * @method integer                  getId()               Returns the current record's "id" value
 * @method integer                  getDisplayFieldId()   Returns the current record's "display_field_id" value
 * @method integer                  getReportId()         Returns the current record's "report_id" value
 * @method OhrmReport               getOhrmReport()       Returns the current record's "OhrmReport" value
 * @method OhrmDisplayField         getOhrmDisplayField() Returns the current record's "OhrmDisplayField" value
 * @method OhrmSelectedDisplayField setId()               Sets the current record's "id" value
 * @method OhrmSelectedDisplayField setDisplayFieldId()   Sets the current record's "display_field_id" value
 * @method OhrmSelectedDisplayField setReportId()         Sets the current record's "report_id" value
 * @method OhrmSelectedDisplayField setOhrmReport()       Sets the current record's "OhrmReport" value
 * @method OhrmSelectedDisplayField setOhrmDisplayField() Sets the current record's "OhrmDisplayField" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmSelectedDisplayField extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_selected_display_field');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('display_field_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('report_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OhrmReport', array(
             'local' => 'report_id',
             'foreign' => 'report_id'));

        $this->hasOne('OhrmDisplayField', array(
             'local' => 'display_field_id',
             'foreign' => 'display_field_id'));
    }
}