<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmViolationType', 'doctrine');

/**
 * BaseOhrmViolationType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $violation_type
 * @property string $description
 * 
 * @method integer           getId()             Returns the current record's "id" value
 * @method string            getViolationType()  Returns the current record's "violation_type" value
 * @method string            getDescription()    Returns the current record's "description" value
 * @method OhrmViolationType setId()             Sets the current record's "id" value
 * @method OhrmViolationType setViolationType()  Sets the current record's "violation_type" value
 * @method OhrmViolationType setDescription()    Sets the current record's "description" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmViolationType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_violation_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('violation_type', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}