<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmJobVacancyAttachment', 'doctrine');

/**
 * BaseOhrmJobVacancyAttachment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $vacancy_id
 * @property string $file_name
 * @property string $file_type
 * @property integer $file_size
 * @property blob $file_content
 * @property integer $attachment_type
 * @property string $comment
 * @property OhrmJobVacancy $OhrmJobVacancy
 * 
 * @method integer                  getId()              Returns the current record's "id" value
 * @method integer                  getVacancyId()       Returns the current record's "vacancy_id" value
 * @method string                   getFileName()        Returns the current record's "file_name" value
 * @method string                   getFileType()        Returns the current record's "file_type" value
 * @method integer                  getFileSize()        Returns the current record's "file_size" value
 * @method blob                     getFileContent()     Returns the current record's "file_content" value
 * @method integer                  getAttachmentType()  Returns the current record's "attachment_type" value
 * @method string                   getComment()         Returns the current record's "comment" value
 * @method OhrmJobVacancy           getOhrmJobVacancy()  Returns the current record's "OhrmJobVacancy" value
 * @method OhrmJobVacancyAttachment setId()              Sets the current record's "id" value
 * @method OhrmJobVacancyAttachment setVacancyId()       Sets the current record's "vacancy_id" value
 * @method OhrmJobVacancyAttachment setFileName()        Sets the current record's "file_name" value
 * @method OhrmJobVacancyAttachment setFileType()        Sets the current record's "file_type" value
 * @method OhrmJobVacancyAttachment setFileSize()        Sets the current record's "file_size" value
 * @method OhrmJobVacancyAttachment setFileContent()     Sets the current record's "file_content" value
 * @method OhrmJobVacancyAttachment setAttachmentType()  Sets the current record's "attachment_type" value
 * @method OhrmJobVacancyAttachment setComment()         Sets the current record's "comment" value
 * @method OhrmJobVacancyAttachment setOhrmJobVacancy()  Sets the current record's "OhrmJobVacancy" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmJobVacancyAttachment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_job_vacancy_attachment');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('vacancy_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('file_name', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('file_type', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('file_size', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('file_content', 'blob', null, array(
             'type' => 'blob',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('attachment_type', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('comment', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OhrmJobVacancy', array(
             'local' => 'vacancy_id',
             'foreign' => 'id'));
    }
}