<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmLicense', 'doctrine');

/**
 * BaseOhrmLicense
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $OhrmEmpLicense
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getName()           Returns the current record's "name" value
 * @method Doctrine_Collection getOhrmEmpLicense() Returns the current record's "OhrmEmpLicense" collection
 * @method OhrmLicense         setId()             Sets the current record's "id" value
 * @method OhrmLicense         setName()           Sets the current record's "name" value
 * @method OhrmLicense         setOhrmEmpLicense() Sets the current record's "OhrmEmpLicense" collection
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmLicense extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_license');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('OhrmEmpLicense', array(
             'local' => 'id',
             'foreign' => 'license_id'));
    }
}