<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Minutes', 'doctrine');

/**
 * BaseMinutes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $min_id
 * @property integer $agn_id
 * @property string $min_desc
 * 
 * @method integer getMinId()    Returns the current record's "min_id" value
 * @method integer getAgnId()    Returns the current record's "agn_id" value
 * @method string  getMinDesc()  Returns the current record's "min_desc" value
 * @method Minutes setMinId()    Sets the current record's "min_id" value
 * @method Minutes setAgnId()    Sets the current record's "agn_id" value
 * @method Minutes setMinDesc()  Sets the current record's "min_desc" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMinutes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('minutes');
        $this->hasColumn('min_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('agn_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('min_desc', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}