<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmLeaveEntitlementAdjustment', 'doctrine');

/**
 * BaseOhrmLeaveEntitlementAdjustment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $adjustment_id
 * @property integer $entitlement_id
 * @property decimal $length_days
 * @property OhrmLeaveEntitlement $OhrmLeaveEntitlement
 * @property OhrmLeaveAdjustment $OhrmLeaveAdjustment
 * 
 * @method integer                        getId()                   Returns the current record's "id" value
 * @method integer                        getAdjustmentId()         Returns the current record's "adjustment_id" value
 * @method integer                        getEntitlementId()        Returns the current record's "entitlement_id" value
 * @method decimal                        getLengthDays()           Returns the current record's "length_days" value
 * @method OhrmLeaveEntitlement           getOhrmLeaveEntitlement() Returns the current record's "OhrmLeaveEntitlement" value
 * @method OhrmLeaveAdjustment            getOhrmLeaveAdjustment()  Returns the current record's "OhrmLeaveAdjustment" value
 * @method OhrmLeaveEntitlementAdjustment setId()                   Sets the current record's "id" value
 * @method OhrmLeaveEntitlementAdjustment setAdjustmentId()         Sets the current record's "adjustment_id" value
 * @method OhrmLeaveEntitlementAdjustment setEntitlementId()        Sets the current record's "entitlement_id" value
 * @method OhrmLeaveEntitlementAdjustment setLengthDays()           Sets the current record's "length_days" value
 * @method OhrmLeaveEntitlementAdjustment setOhrmLeaveEntitlement() Sets the current record's "OhrmLeaveEntitlement" value
 * @method OhrmLeaveEntitlementAdjustment setOhrmLeaveAdjustment()  Sets the current record's "OhrmLeaveAdjustment" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmLeaveEntitlementAdjustment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_leave_entitlement_adjustment');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('adjustment_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('entitlement_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('length_days', 'decimal', 4, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             'scale' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OhrmLeaveEntitlement', array(
             'local' => 'entitlement_id',
             'foreign' => 'id'));

        $this->hasOne('OhrmLeaveAdjustment', array(
             'local' => 'adjustment_id',
             'foreign' => 'id'));
    }
}