<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmPayrollconfig', 'doctrine');

/**
 * BaseOhrmPayrollconfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property decimal $personal_relief
 * @property decimal $insurance_relief
 * @property decimal $spouse_relief
 * @property decimal $qualifying_relief
 * @property decimal $other_relief
 * @property string $daily_rate
 * @property string $hourly_rate
 * @property string $system_url
 * @property integer $expiry_years
 * @property integer $manual_cardprint
 * 
 * @method integer           getId()                Returns the current record's "id" value
 * @method decimal           getPersonalRelief()    Returns the current record's "personal_relief" value
 * @method decimal           getInsuranceRelief()   Returns the current record's "insurance_relief" value
 * @method decimal           getSpouseRelief()      Returns the current record's "spouse_relief" value
 * @method decimal           getQualifyingRelief()  Returns the current record's "qualifying_relief" value
 * @method decimal           getOtherRelief()       Returns the current record's "other_relief" value
 * @method string            getDailyRate()         Returns the current record's "daily_rate" value
 * @method string            getHourlyRate()        Returns the current record's "hourly_rate" value
 * @method string            getSystemUrl()         Returns the current record's "system_url" value
 * @method integer           getExpiryYears()       Returns the current record's "expiry_years" value
 * @method integer           getManualCardprint()   Returns the current record's "manual_cardprint" value
 * @method OhrmPayrollconfig setId()                Sets the current record's "id" value
 * @method OhrmPayrollconfig setPersonalRelief()    Sets the current record's "personal_relief" value
 * @method OhrmPayrollconfig setInsuranceRelief()   Sets the current record's "insurance_relief" value
 * @method OhrmPayrollconfig setSpouseRelief()      Sets the current record's "spouse_relief" value
 * @method OhrmPayrollconfig setQualifyingRelief()  Sets the current record's "qualifying_relief" value
 * @method OhrmPayrollconfig setOtherRelief()       Sets the current record's "other_relief" value
 * @method OhrmPayrollconfig setDailyRate()         Sets the current record's "daily_rate" value
 * @method OhrmPayrollconfig setHourlyRate()        Sets the current record's "hourly_rate" value
 * @method OhrmPayrollconfig setSystemUrl()         Sets the current record's "system_url" value
 * @method OhrmPayrollconfig setExpiryYears()       Sets the current record's "expiry_years" value
 * @method OhrmPayrollconfig setManualCardprint()   Sets the current record's "manual_cardprint" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmPayrollconfig extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_payrollconfig');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('personal_relief', 'decimal', 6, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 6,
             'scale' => '2',
             ));
        $this->hasColumn('insurance_relief', 'decimal', 6, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 6,
             'scale' => '2',
             ));
        $this->hasColumn('spouse_relief', 'decimal', 6, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 6,
             'scale' => '2',
             ));
        $this->hasColumn('qualifying_relief', 'decimal', 6, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 6,
             'scale' => '2',
             ));
        $this->hasColumn('other_relief', 'decimal', 6, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 6,
             'scale' => '2',
             ));
        $this->hasColumn('daily_rate', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('hourly_rate', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('system_url', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('expiry_years', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '2',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('manual_cardprint', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}