<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Gradechange', 'doctrine');

/**
 * BaseGradechange
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $employee_id
 * @property string $previous_grade
 * @property string $current_grade
 * @property string $effected
 * 
 * @method integer     getId()             Returns the current record's "id" value
 * @method integer     getEmployeeId()     Returns the current record's "employee_id" value
 * @method string      getPreviousGrade()  Returns the current record's "previous_grade" value
 * @method string      getCurrentGrade()   Returns the current record's "current_grade" value
 * @method string      getEffected()       Returns the current record's "effected" value
 * @method Gradechange setId()             Sets the current record's "id" value
 * @method Gradechange setEmployeeId()     Sets the current record's "employee_id" value
 * @method Gradechange setPreviousGrade()  Sets the current record's "previous_grade" value
 * @method Gradechange setCurrentGrade()   Sets the current record's "current_grade" value
 * @method Gradechange setEffected()       Sets the current record's "effected" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGradechange extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gradechange');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('employee_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('previous_grade', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('current_grade', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('effected', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}