<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Editjobdetails', 'doctrine');

/**
 * BaseEditjobdetails
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $employee_id
 * @property integer $job_title
 * @property integer $job_category
 * @property integer $department
 * @property integer $location
 * @property string $previouscurrent
 * @property integer $is_promotion
 * @property integer $is_transfer
 * 
 * @method integer        getId()              Returns the current record's "id" value
 * @method integer        getEmployeeId()      Returns the current record's "employee_id" value
 * @method integer        getJobTitle()        Returns the current record's "job_title" value
 * @method integer        getJobCategory()     Returns the current record's "job_category" value
 * @method integer        getDepartment()      Returns the current record's "department" value
 * @method integer        getLocation()        Returns the current record's "location" value
 * @method string         getPreviouscurrent() Returns the current record's "previouscurrent" value
 * @method integer        getIsPromotion()     Returns the current record's "is_promotion" value
 * @method integer        getIsTransfer()      Returns the current record's "is_transfer" value
 * @method Editjobdetails setId()              Sets the current record's "id" value
 * @method Editjobdetails setEmployeeId()      Sets the current record's "employee_id" value
 * @method Editjobdetails setJobTitle()        Sets the current record's "job_title" value
 * @method Editjobdetails setJobCategory()     Sets the current record's "job_category" value
 * @method Editjobdetails setDepartment()      Sets the current record's "department" value
 * @method Editjobdetails setLocation()        Sets the current record's "location" value
 * @method Editjobdetails setPreviouscurrent() Sets the current record's "previouscurrent" value
 * @method Editjobdetails setIsPromotion()     Sets the current record's "is_promotion" value
 * @method Editjobdetails setIsTransfer()      Sets the current record's "is_transfer" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEditjobdetails extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('editjobdetails');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('employee_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('job_title', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('job_category', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('department', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('location', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('previouscurrent', 'string', 2, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('is_promotion', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('is_transfer', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}