<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmLogin', 'doctrine');

/**
 * BaseOhrmLogin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $user_name
 * @property string $user_role_name
 * @property integer $user_role_predefined
 * @property timestamp $login_time
 * 
 * @method integer   getId()                   Returns the current record's "id" value
 * @method integer   getUserId()               Returns the current record's "user_id" value
 * @method string    getUserName()             Returns the current record's "user_name" value
 * @method string    getUserRoleName()         Returns the current record's "user_role_name" value
 * @method integer   getUserRolePredefined()   Returns the current record's "user_role_predefined" value
 * @method timestamp getLoginTime()            Returns the current record's "login_time" value
 * @method OhrmLogin setId()                   Sets the current record's "id" value
 * @method OhrmLogin setUserId()               Sets the current record's "user_id" value
 * @method OhrmLogin setUserName()             Sets the current record's "user_name" value
 * @method OhrmLogin setUserRoleName()         Sets the current record's "user_role_name" value
 * @method OhrmLogin setUserRolePredefined()   Sets the current record's "user_role_predefined" value
 * @method OhrmLogin setLoginTime()            Sets the current record's "login_time" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmLogin extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_login');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('user_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('user_role_name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('user_role_predefined', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('login_time', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}