<?php

/**
 * BaseIncomeTaxSlab
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tb_id
 * @property integer $minfigure
 * @property integer $maxfigure
 * @property integer $percentage
 * 
 * @method integer       getTbId()       Returns the current record's "tb_id" value
 * @method integer       getMinfigure()  Returns the current record's "minfigure" value
 * @method integer       getMaxfigure()  Returns the current record's "maxfigure" value
 * @method integer       getPercentage() Returns the current record's "percentage" value
 * @method IncomeTaxSlab setTbId()       Sets the current record's "tb_id" value
 * @method IncomeTaxSlab setMinfigure()  Sets the current record's "minfigure" value
 * @method IncomeTaxSlab setMaxfigure()  Sets the current record's "maxfigure" value
 * @method IncomeTaxSlab setPercentage() Sets the current record's "percentage" value
 * 
 * @package    orangehrm
 * @subpackage model\payroll\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIncomeTaxSlab extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('incometax_slab');
        $this->hasColumn('tb_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('minfigure', 'integer', 100, array(
             'type' => 'integer',
             'length' => 100,
             ));
        $this->hasColumn('maxfigure', 'integer', 100, array(
             'type' => 'integer',
             'length' => 100,
             ));
        $this->hasColumn('percentage', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}