<?php

/**
 * CasualhoursTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CasualhoursTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CasualhoursTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Casualhours');
    }
}