<?php

/**
 * HsHrEmpBasicsalaryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HsHrEmpBasicsalaryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HsHrEmpBasicsalaryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HsHrEmpBasicsalary');
    }
    
     public static function  getPayslipForMonth($empno,$month){
             $q = Doctrine_Query::create()
                            ->from('HsHrEmpBasicsalary')
                         ->where(" `emp_number`=$empno")
  ->andWhere("DATE_FORMAT(`payslipdate`,'%m/%Y') like '$month'");
            $q->execute();
        
      return $q->fetchOne();
    }
    
         public static function  getEmpBasicSalary($empno){
             HsHrEmpBasicsalary::$_null;
             $q = Doctrine_Query::create()
                            ->from('HsHrEmpBasicsalary')
                         ->where(" `emp_number`=$empno")
  ->andWhere("salary_component like '%Basic%' ");
            $q->execute();
        
 $salary=$q->fetchOne();
 if(is_object($salary)){
 return $salary->getEbsalBasicSalary();
 }else{
     return 0;
 }
    }
	
	 public static function  getSalaryCode($empno){
             HsHrEmpBasicsalary::$_null;
             $q = Doctrine_Query::create()
                            ->from('HsHrEmpBasicsalary')
                         ->where(" `emp_number`=$empno")
  ->andWhere("salary_component like '%Basic%' ");
            $q->execute();
        
 $salary=$q->fetchOne();
 if(is_object($salary)){
 return $salary->getSalGrdCode();
 }else{
     return 0;
 }
    }
    
    public static function  getEmployeeCountyBySalaryCode($gradecode){
             HsHrEmpBasicsalary::$_null;
             $q = Doctrine_Query::create()
                            ->from('HsHrEmpBasicsalary bs')
                      
                         ->innerJoin('bs.HsHrEmployee he ')
                         ->where(" bs.sal_grd_code=$gradecode")
                     ->andWhere("he.termination_id is NULL")
  ->andWhere("bs.salary_component like '%Basic%' ")
             ->groupBy("bs.emp_number");
          return $q->count();

    }
    
	public static function  getEmployeeCountBySalaryCodeAndLocation($gradecode,$location){
		$completeQuery="SELECT COUNT(hs_hr_emp_basicsalary.emp_number) as counted FROM `hs_hr_emp_basicsalary` JOIN `hs_hr_emp_locations` on `hs_hr_emp_basicsalary`.emp_number=hs_hr_emp_locations.emp_number WHERE hs_hr_emp_locations.location_id=? AND sal_grd_code=? and salary_component like '%Basic%'";
		$conn = Doctrine_Manager::connection();
        $statement = $conn->prepare($completeQuery);
        $result = $statement->execute(array($location,$gradecode));
	 $returned=$statement->fetchAll();
	 return $returned[0]['counted'];

    }
	
	
	
     public static function  getEmpHouseAllowance($empno){
             HsHrEmpBasicsalary::$_null;
             $q = Doctrine_Query::create()
                            ->from('HsHrEmpBasicsalary')
                         ->where(" `emp_number`=$empno")
  ->andWhere("salary_component like '%House Allowance%' ");
            $q->execute();
 $salary=$q->fetchOne();
 if(is_object($salary)){
 return $salary->getEbsalBasicSalary();
 }else{
     return 0;
 }
    }
    
     public static function getEmpDailyPay($empno) {
  
        $salary = HsHrEmpBasicsalaryTable::getEmpBasicSalary($empno);
        $dailypay = round(($salary * 12) / 365);
        return round($dailypay,2);
    }
    
}