<?php

/**
 * HsHrEmpdefaultpaymodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HsHrEmpdefaultpaymodeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HsHrEmpdefaultpaymodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HsHrEmpdefaultpaymode');
    }
    
     public static function checkIfPaymentMethodExists($empno,$paymethod=""){
           $paymethodd=Doctrine_Query::create()->from ('HsHrEmpdefaultpaymode')
             ->where(" `empnumber` = '$empno' ")
                  // ->andWhere(" `paymentmethod` = '$paymethod' ")
      ->fetchArray();
return $paymethodd[0];
     }
    
     
     public static function updateActivePayMethod($empno,$paymethod){
    
          $payrollmonth= Doctrine_Query::create()->from ('HsHrEmpdefaultpaymode')
             ->Where(" `empnumber` ='$empno' ")
      ->fetchArray();
         
      $payrollmonthnew=self::getInstance()->find($payrollmonth[0]['id']);
       
          $payrollmonthnew->setPaymentMethod($paymethod);
       
          $payrollmonthnew->save();
          
     }
    
}