<?php

/**
 * HsHrModuleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HsHrModuleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HsHrModuleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HsHrModule');
    }
}