<?php

/**
 * HsHrUniqueIdTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HsHrUniqueIdTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HsHrUniqueIdTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HsHrUniqueId');
    }
}