<?php

/**
 * HsHrEmpPassportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HsHrEmpPassportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HsHrEmpPassportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HsHrEmpPassport');
    }
}