<?php

/**
 * HsHrEmpChildrenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HsHrEmpChildrenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HsHrEmpChildrenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HsHrEmpChildren');
    }
}