<?php

/**
 * MeetingTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MeetingTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MeetingTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MeetingType');
    }
}