<?php

/**
 * NssfTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NssfTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NssfTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Nssf');
    }
    public static function getConfiguration(){
    return self::getInstance()->find(1);
    }
    
}