<?php

/**
 * OhrmProjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmProjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmProjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmProject');
    }
}