<?php

/**
 * OhrmProjectAdminTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmProjectAdminTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmProjectAdminTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmProjectAdmin');
    }
}