<?php

/**
 * Ohrm_InterviewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Ohrm_InterviewTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Ohrm_InterviewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ohrm_Interview');
    }
    
    public static function getAllInterviews(){
        return self::getInstance()->findAll();
    }
       public static function getInterview($id){
        return self::getInstance()->find($id);
    }
    
     public static function hydrateCandidatesFirstName(){
        $allinterviews=array();
        $q = Doctrine_Query::create()
                            ->from('Ohrm_Interview')
                         ->where(" `status`='passed'");
             $q->execute();
             $results=$q->fetchArray();
             $allinterviews[""]="First Name";
             foreach ($results as $result) {
                $allinterviews[$result["candidate_first_name"]]=$result["candidate_first_name"];
             }
             
             return $allinterviews;
    }
public static function hydrateCandidatesMiddleName(){
        $allinterviews=array();
        $q = Doctrine_Query::create()
                            ->from('Ohrm_Interview')
                         ->where(" `status`='passed'");
             $q->execute();
             $results=$q->fetchArray();
             $allinterviews[""]="Middle Name";
             foreach ($results as $result) {
                $allinterviews[$result["candidate_middle_name"]]=$result["candidate_middle_name"];
             }
             
             return $allinterviews;
    }
    public static function hydrateCandidatesLastName(){
        $allinterviews=array();
        $q = Doctrine_Query::create()
                            ->from('Ohrm_Interview')
                         ->where(" `status` ='passed'");
             $q->execute();
             $results=$q->fetchArray();
             $allinterviews[""]="Last Name";
             foreach ($results as $result) {
                $allinterviews[$result["candidate_last_name"]]=$result["candidate_last_name"];
             }
             
             return $allinterviews;
    }

    public static function hydrateInterviews(){
        $allinterviews=array();
        $q = Doctrine_Query::create()
                            ->from('Ohrm_Interview')
                         ->where(" `status` !='completed'");
             $q->execute();
             $results=$q->fetchArray();
             
             foreach ($results as $result) {
                $allinterviews[$result["id"]]=$result["candidate_first_name"]." ".$result["candidate_middle_name"]."=> ". $result["interviewer_name"]."(".date("d-m-Y",  strtotime($result["interview_date"])).")";
             }
             
             return $allinterviews;
    }
}