<?php

/**
 * OhrmHolidayTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmHolidayTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmHolidayTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmHoliday');
    }
}