<?php

/**
 * OhrmLanguageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmLanguageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmLanguageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmLanguage');
    }
}