<?php

/**
 * OhrmGroupFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmGroupFieldTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmGroupFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmGroupField');
    }
}