<?php

/**
 * OhrmTimesheetActionLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmTimesheetActionLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmTimesheetActionLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmTimesheetActionLog');
    }
}