<?php

/**
 * OhrmOrganizationGenInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmOrganizationGenInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmOrganizationGenInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmOrganizationGenInfo');
    }
    
    
    
    public static function getOrganizationInfo(){
        return self::getInstance()->findBy("id",1);
    }
}