<?php

/**
 * OhrmLeaveTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmLeaveTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmLeaveTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmLeaveType');
    }
}