<?php

/**
 * OhrmScreenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmScreenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmScreenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmScreen');
    }
    
          public static function  getScreenName($screenid){
           
             $q = Doctrine_Query::create()
                            ->from('OhrmScreen')
                         ->where(" `id`=$screenid");
 
            $q->execute();
        
 $salary=$q->fetchOne();
 if(is_object($salary)){
 return $salary->name;
 }else{
     return null;
 }
    }
}