<?php

/**
 * OhrmJobCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmJobCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmJobCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmJobCategory');
    }
}