<?php

/**
 * OhrmLeaveEntitlementAdjustmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmLeaveEntitlementAdjustmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmLeaveEntitlementAdjustmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmLeaveEntitlementAdjustment');
    }
}