<?php

/**
 * OhrmBankBranchTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmBankBranchTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmBankBranchTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmBankBranch');
    }
    
     public static function getBranchById($id) {
        try {
            return  self::getInstance()->find($id);
        } catch (Exception $e) {
            throw new DaoException($e->getMessage());
        }
    }  
    
     public static function getBankFromBranch($id) {

            $branch=self::getInstance()->find($id);
            $bankid=$branch->getBankId();
    $bankdetails= Ohrm_BankTable::getBankById($bankid);
   $bankandbranch= $bankdetails->getBankName()."-".$branch->getBranchName();
   return $bankandbranch;
      
    }

        public static function getBankDetailsFromBranch($id) {

            $branch=self::getInstance()->find($id);
            $bankid=$branch->getBankId();
    $bankdetails= Ohrm_BankTable::getBankById($bankid);
 
   return $bankdetails;
      
    }
     public static function hydrateBankBranches() {
        try {
$deductions=  self::getInstance()->findAll();
foreach ($deductions as $deduction) {
    $bankid=$deduction->getBankId();
    $bankdetails= Ohrm_BankTable::getBankById($bankid);
    $choices[$deduction->getId()]=$bankdetails->getBankName()."-".$deduction->getBranchName();
}
return $choices;
        } catch (Exception $e) {
            throw new DaoException($e->getMessage());
        }
    }
    
     public static function deleteBranch($id) {
        try {
             $deletequery=  self::getInstance()
  ->createQuery()
  ->delete()
  ->where(" `id`=$id")
  ->execute();
            return true;
        } catch (Exception $e) {
            throw new DaoException($e->getMessage());
        }
    }
    
    
    
}