<?php

/**
 * OhrmRoleUserSelectionRuleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmRoleUserSelectionRuleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmRoleUserSelectionRuleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmRoleUserSelectionRule');
    }
}