<?php

/**
 * OhrmBudgetExpensesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmBudgetExpensesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmBudgetExpensesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmBudgetExpenses');
    }
}