<?php

/**
 * OhrmSelectedDisplayFieldGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmSelectedDisplayFieldGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmSelectedDisplayFieldGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmSelectedDisplayFieldGroup');
    }
}