<?php

/**
 * OhrmAuthProviderExtraDetailsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmAuthProviderExtraDetailsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmAuthProviderExtraDetailsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmAuthProviderExtraDetails');
    }
}