<?php

/**
 * OhrnTrainingSessionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmTrainingSessionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrnTrainingSessionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmTrainingSession');
    }
    
     public static function getSession($id){
        return self::getInstance()->find($id);
    }
}