<?php

/**
 * OhrmReportGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmReportGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmReportGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmReportGroup');
    }
}