<?php

/**
 * OhrmEmploymentStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmEmploymentStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmEmploymentStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmEmploymentStatus');
    }
}