<?php

/**
 * OhrmModuleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmModuleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmModuleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmModule');
    }
}