<?php

/**
 * OhrmSummaryDisplayFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmSummaryDisplayFieldTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmSummaryDisplayFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmSummaryDisplayField');
    }
}