<?php

/**
 * OhrmEmailNotificationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmEmailNotificationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmEmailNotificationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmEmailNotification');
    }
}