<?php

/**
 * OhrmLeaveCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmLeaveCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmLeaveCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmLeaveComment');
    }
}