<?php

/**
 * OhrmCandidateinterviewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmCandidateinterviewTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmCandidateinterviewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmCandidateinterview');
    }
}