<?php

/**
 * OhrmUpgradeHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmUpgradeHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmUpgradeHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmUpgradeHistory');
    }
}