<?php

/**
 * OhrmEmpsalaryDeductionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmEmpsalaryDeductionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmEmpsalaryDeductionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmEmpsalaryDeductions');
    }
}