<?php

/**
 * OhrmLoantransactionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmLoantransactionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmLoantransactionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmLoantransactions');
    }
}