<?php

/**
 * OhrmViolationTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmViolationTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmViolationTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmViolationType');
    }
    
    public static function getAllViolations(){
        try {
        return Doctrine_Query::create()->from ('OhrmViolationType')   
                 ->where(" `id`> 0")
            // ->orderBy("`violation_type` ASC")
      ->execute();
        } catch (Exception $e) {
            throw new DaoException($e->getMessage());
        }
    }
    
     public static function getViolation($id){
        return self::getInstance()->find($id);
    }
    
}