<?php

/**
 * OhrmAdvancedReportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmAdvancedReportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmAdvancedReportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmAdvancedReport');
    }
}