<?php

/**
 * OhrmMenuItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmMenuItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmMenuItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmMenuItem');
    }
}