<?php

/**
 * OhrmLicenseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmLicenseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmLicenseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmLicense');
    }
}