<?php

/**
 * OhrmBenefitsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmBenefitsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmBenefitsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmBenefits');
    }
}