<?php

/**
 * OhrmTrainingParticipantsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmTrainingParticipantsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmTrainingParticipantsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmTrainingParticipants');
    }
}