<?php

/**
 * OhrmDisplayFieldGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmDisplayFieldGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmDisplayFieldGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmDisplayFieldGroup');
    }
}