<?php

/**
 * OhrmSelectedDisplayFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmSelectedDisplayFieldTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmSelectedDisplayFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmSelectedDisplayField');
    }
}