<?php

/**
 * OhrmIncidentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmIncidentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmIncidentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmIncidents');
    }
}