<?php

/**
 * OhrmAvailableGroupFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmAvailableGroupFieldTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmAvailableGroupFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmAvailableGroupField');
    }
}