<?php

/**
 * Ohrm_InterviewSetupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Ohrm_InterviewSetupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Ohrm_InterviewSetupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ohrm_InterviewSetup');
    }
    
    public static function getBenchmarks(){
        return self::getInstance()->findAll();
    }
    
       public static function getBenchmark($id){
        return self::getInstance()->findOneBy("id", $id);
    }
     public static function hydrateQuestions(){
         $allquestions=array();
    $questions= self::getInstance()->findAll();
    foreach ($questions as $question) {
$allquestions[$question->getId()]=$question->getQuestion()."(".$question->getWeight()." pts)";

}
return $allquestions;;
    }
    
    
}