<?php

/**
 * OhrmJobVacancyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmJobVacancyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmJobVacancyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmJobVacancy');
    }
}