<?php

/**
 * OhrmDisplayFieldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmDisplayFieldTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmDisplayFieldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmDisplayField');
    }
}