<?php

/**
 * SalaryChangeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SalaryChangeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SalaryChangeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SalaryChange');
    }
}