<?php

/**
 * UserActionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserActionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserActionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserActions');
    }
}